export const initialTeams = [
  { id: 1, name: 'Equipe Alfa' },
  { id: 2, name: 'Equipe Beta' },
  { id: 3, name: 'Equipe Gama' },
]

export const initialBrokers = [
  {
    id: 1,
    name: 'Ricardo Mendes',
    email: 'ricardo.mendes@imob.com',
    phone: '(11) 98765-4321',
    region: 'Unidade Sul',
    teamId: 1,
    teamName: 'Equipe Alfa',
    position: 'Sênior',
    leads: 150,
    sales: 45,
    conversionRate: 30,
    vgv: 12500000,
    active: true,
    aiAnalysis:
      'Desempenho consistente e alta taxa de conversão nas etapas iniciais. Demonstra forte capacidade de negociação e excelente comunicação.',
    deficiencies: ['Pequena queda no acompanhamento pós-venda (follow-up após assinatura)'],
    trainingRecommendation: 'Masterclass: Fidelização de Clientes',
  },
  {
    id: 2,
    name: 'Ana Paula Silva',
    email: 'ana.silva@imob.com',
    phone: '(11) 97777-6666',
    region: 'Unidade Norte',
    teamId: 1,
    teamName: 'Equipe Alfa',
    position: 'Pleno',
    leads: 200,
    sales: 42,
    conversionRate: 21,
    vgv: 11200000,
    active: true,
    aiAnalysis:
      'Boa performance geral, porém apresenta ligeira queda na conversão de leads frios. Follow-up poderia ser otimizado.',
    deficiencies: ['Follow-up ineficiente em leads frios', 'Demora na primeira resposta (SLA)'],
    trainingRecommendation: 'Workshop: Estratégias de Follow-up e Reengajamento',
  },
  {
    id: 3,
    name: 'Carlos Eduardo',
    email: 'carlos.edu@imob.com',
    phone: '(11) 96666-5555',
    region: 'Unidade Leste',
    teamId: 2,
    teamName: 'Equipe Beta',
    position: 'Júnior',
    leads: 120,
    sales: 12,
    conversionRate: 10,
    vgv: 4500000,
    active: true,
    aiAnalysis:
      'Baixa conversão na etapa de negociação (15% abaixo da média). Tempo de resposta aos leads está acima do aceitável (lento).',
    deficiencies: [
      'Baixa conversão na etapa de fechamento',
      'Lentidão no primeiro contato com lead',
    ],
    trainingRecommendation: 'Treinamento Intensivo de Negociação e Gestão de Tempo',
  },
  {
    id: 4,
    name: 'Mariana Costa',
    email: 'mariana.costa@imob.com',
    phone: '(11) 95555-4444',
    region: 'Unidade Oeste',
    teamId: 3,
    teamName: 'Equipe Gama',
    position: 'Sênior',
    leads: 140,
    sales: 35,
    conversionRate: 25,
    vgv: 8500000,
    active: false,
    aiAnalysis:
      'Histórico de vendas sólido, atualmente inativa no sistema. Mantinha excelentes índices de satisfação dos clientes.',
    deficiencies: [],
    trainingRecommendation: null,
  },
  {
    id: 5,
    name: 'Marcos Gomes',
    email: 'marcos.gomes@imob.com',
    phone: '(11) 94444-3333',
    region: 'Unidade Norte',
    teamId: 1,
    teamName: 'Equipe Alfa',
    position: 'Pleno',
    leads: 32,
    sales: 6,
    conversionRate: 18,
    vgv: 1500000,
    active: true,
    aiAnalysis: 'Desempenho dentro da média, necessita aumentar o volume de prospecção.',
    deficiencies: ['Baixo volume de ligações diárias'],
    trainingRecommendation: 'Prospecção Ativa na Prática',
  },
  {
    id: 6,
    name: 'Juliana Fernandes',
    email: 'juliana.f@imob.com',
    phone: '(11) 93333-2222',
    region: 'Unidade Sul',
    teamId: 2,
    teamName: 'Equipe Beta',
    position: 'Júnior',
    leads: 85,
    sales: 22,
    conversionRate: 26,
    vgv: 7800000,
    active: true,
    aiAnalysis: 'Excelente conversão apesar de ser júnior. Boa argumentação.',
    deficiencies: [],
    trainingRecommendation: 'Técnicas Avançadas de Fechamento',
  },
  {
    id: 7,
    name: 'Rafael Oliveira',
    email: 'rafael.o@imob.com',
    phone: '(11) 92222-1111',
    region: 'Unidade Leste',
    teamId: 3,
    teamName: 'Equipe Gama',
    position: 'Pleno',
    leads: 45,
    sales: 4,
    conversionRate: 8.5,
    vgv: 2800000,
    active: true,
    aiAnalysis: 'Conversão baixa nas etapas finais do funil. Demora no envio de propostas.',
    deficiencies: ['Lentidão na elaboração de propostas'],
    trainingRecommendation: 'Agilidade e Organização em Vendas',
  },
]
