export const initialBrokers = [
  {
    id: 1,
    name: 'Ricardo Mendes',
    email: 'ricardo.mendes@imob.com',
    phone: '(11) 98765-4321',
    region: 'Unidade Sul',
    position: 'Sênior',
    leads: 150,
    sales: 45,
    conversionRate: 30,
    vgv: 12500000,
    active: true,
    aiAnalysis:
      'Desempenho consistente e alta taxa de conversão nas etapas iniciais. Demonstra forte capacidade de negociação e excelente comunicação.',
    deficiencies: ['Pequena queda no acompanhamento pós-venda (follow-up após assinatura)'],
    trainingRecommendation: 'Masterclass: Fidelização de Clientes',
  },
  {
    id: 2,
    name: 'Ana Paula Silva',
    email: 'ana.silva@imob.com',
    phone: '(11) 97777-6666',
    region: 'Unidade Norte',
    position: 'Pleno',
    leads: 200,
    sales: 42,
    conversionRate: 21,
    vgv: 11200000,
    active: true,
    aiAnalysis:
      'Boa performance geral, porém apresenta ligeira queda na conversão de leads frios. Follow-up poderia ser otimizado.',
    deficiencies: ['Follow-up ineficiente em leads frios', 'Demora na primeira resposta (SLA)'],
    trainingRecommendation: 'Workshop: Estratégias de Follow-up e Reengajamento',
  },
  {
    id: 3,
    name: 'Carlos Eduardo',
    email: 'carlos.edu@imob.com',
    phone: '(11) 96666-5555',
    region: 'Unidade Leste',
    position: 'Júnior',
    leads: 120,
    sales: 12,
    conversionRate: 10,
    vgv: 4500000,
    active: true,
    aiAnalysis:
      'Baixa conversão na etapa de negociação (15% abaixo da média). Tempo de resposta aos leads está acima do aceitável (lento).',
    deficiencies: [
      'Baixa conversão na etapa de fechamento',
      'Lentidão no primeiro contato com lead',
    ],
    trainingRecommendation: 'Treinamento Intensivo de Negociação e Gestão de Tempo',
  },
  {
    id: 4,
    name: 'Mariana Costa',
    email: 'mariana.costa@imob.com',
    phone: '(11) 95555-4444',
    region: 'Unidade Oeste',
    position: 'Sênior',
    leads: 140,
    sales: 35,
    conversionRate: 25,
    vgv: 8500000,
    active: false,
    aiAnalysis:
      'Histórico de vendas sólido, atualmente inativa no sistema. Mantinha excelentes índices de satisfação dos clientes.',
    deficiencies: [],
    trainingRecommendation: null,
  },
]
